name: ${project.name}
main: com.poixson.commonmc.pxnCommonPlugin
version: ${project.version}
api-version: ${spigot-short-version}
load: STARTUP
softdepend: [ Multiverse-Core ]
authors: [ lorenzop ]
website: ${project.url}
description: ${project.description}
