name: ${project.name}
main: com.poixson.commonmc.pxnCommonPlugin
version: ${project.version}
api-version: ${spigot-short-version}
load: STARTUP
softdepend:
  - Multiverse-Core
  - WorldEdit
authors: [ lorenzop ]
website: ${project.url}
description: ${project.description}
permission-message: "You don't have permission to use this command."
commands:
    tps:
        description: "Display the average ticks per second"
        usage: "Usage: /tps <cmd>"
    lag:
        description: "Display the average ticks per second"
        usage: "Usage: /lag <cmd>"
    mem:
        description: "Display the average ticks per second"
        usage: "Usage: /mem <cmd>"
    memory:
        description: "Display the average ticks per second"
        usage: "Usage: /memory <cmd>"
permissions:
    pxncommon.*:
        default: op
        description: Gives access to all pxn common commands.
        children:
            pxncommon.updates: true
    pxncommon.updates:
        default: op
        description: Receive notices of plugin updates.
