name: ${project.name}
main: com.poixson.commonmc.pxnCommonPlugin
version: ${project.version}
api-version: ${spigot-short-version}
load: STARTUP
softdepend: [ Multiverse-Core ]
authors: [ lorenzop ]
website: ${project.url}
description: ${project.description}
permissions:
    pxncommon.*:
        default: op
        description: Gives access to all pxn common commands.
        children:
            pxncommon.updates: true
    pxncommon.updates:
        default: op
        description: Receive notices of plugin updates.
